name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  build-backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.9.5
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - uses: marceloprado/has-changed-path@v1
        id: changed-back
        with:
          paths: server client/src/shared
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: pnpm install --frozen-lockfile
      # Build
      - name: Build
        run: pnpm run build
      - name: ESLint
        run: pnpm run eslint

  build-frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.9.5
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - uses: marceloprado/has-changed-path@v1
        id: changed-front
        with:
          paths: client
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: pnpm install --frozen-lockfile
      # Build
      - name: Build
        run: pnpm run build
      - name: ESLint
        run: pnpm run eslint
